version: "3.11"

services:
  simple-chat-db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: simple_chat_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  simple-chat:
    build: .
    depends_on:
      - simple-chat-db
    environment:
      MIX_ENV: dev
      DB_HOST: simple-chat-db
      DB_NAME: simple_chat_dev
      DB_USER: admin
      DB_PASS: admin
    ports:
      - "4000:4000"
    volumes:
     - .:/app

volumes:
  postgres_data:
